### ISSUE TITLE
Can't compile wine-3d3adapter.

### ISSUE THREAD

**Issue by fenexomega** [brettlyons/pkgbuilds-nine#1] opened 2014-12-22 16:29 UTC
After a makepkg in wine-d3dadpter-nine, make exits with a error on build():

```
../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c: In function ‘DRI2FallbackInit’:
../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c:155:45: error: ‘EGL_PLATFORM_X11_EXT’ undeclared (first use in this function)
     display = eglGetPlatformDisplayEXT_func(EGL_PLATFORM_X11_EXT, dpy, NULL);
                                             ^
../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c:155:45: note: each undeclared identifier is reported only once for each function it appears in
Makefile:316: recipe for target 'dri3.o' failed
make[1]: *** [dri3.o] Error 1
make[1]: Leaving directory '/home/jordy/Projects/pkgbuilds-nine/wine-d3dadpter-nine/src/wine-d3dadapter-git-64-build/dlls/winex11.drv'
Makefile:16868: recipe for target 'dlls/winex11.drv' failed
```

Don't know how to procceed in this one. I'm sure I did everything in order, like installing the mesa packages before compilling the wine ones. What should I do?

**Comment by brettlyons** [comment] 2014-12-24 20:58
Might ask about it in the #d3d9 channel on the freenode.org IRC server.

Also, you might have just happened to pull the source during a patch that
broke something, and if that's the case, trying again in a day or two
should fix it.

Have you checked the Ixit wiki?  There might be some info there thats
useful to you.

~Brett

On Mon, Dec 22, 2014 at 9:29 AM, Jordy notifications@github.com wrote:

> After a makepkg in wine-d3dadpter-nine, make exits with a error on build():
> 
> ../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c: In function ‘DRI2FallbackInit’:
> ../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c:155:45: error: ‘EGL_PLATFORM_X11_EXT’ undeclared (first use in this function)
>      display = eglGetPlatformDisplayEXT_func(EGL_PLATFORM_X11_EXT, dpy, NULL);
>                                              ^
> ../../../wine-d3dadapter-git/dlls/winex11.drv/dri3.c:155:45: note: each undeclared identifier is reported only once for each function it appears in
> Makefile:316: recipe for target 'dri3.o' failed
> make[1]: **\* [dri3.o] Error 1
> make[1]: Leaving directory '/home/jordy/Projects/pkgbuilds-nine/wine-d3dadpter-nine/src/wine-d3dadapter-git-64-build/dlls/winex11.drv'
> Makefile:16868: recipe for target 'dlls/winex11.drv' failed
> 
> Don't know how to procceed in this one. I'm sure I did everything in
> order, like installing the mesa packages before compilling the wine ones.
> What should I do?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brettlyons/pkgbuilds-nine/issues/1.

## 

For Naropa IT assistance, please email helpdesk@naropa.edu

**Comment by NP-Hardass** [comment] 2015-02-21 00:41
What was the resolution for this?

**Comment by brettlyons** [comment] 2015-02-21 19:25
I don't know, it hasn't come up again, and Eriner in #d3d9 is using the PKGBUILDs without this issue.  For now I'm closing because it hasn't been reproduced in a while, if it comes up again, I'll re-open.

**Closed as completed by brettlyons** 2015-02-21 19:25 UTC

**Comment by diego7319** [comment] 2015-03-31 23:35
i think i also had it  :
Makefile:317: fallo en las instrucciones para el objetivo 'dri3.o'
make[1]: **\* [dri3.o] Error 1
make[1]: se sale del directorio '/tmp/yaourt-tmp-diego/aur-wine-d3dadapter-git/src/wine-d3dadapter-git-64-build/dlls/winex11.drv'
Makefile:14346: fallo en las instrucciones para el objetivo 'dlls/winex11.drv'
make: **\* [dlls/winex11.drv] Error 2
[EDIT]
I was installing it with yaourt, just installed well with cloning git ./configure and make

**Comment by lifeofdan** [comment] 2015-08-02 04:04
I am having the same issue. Although, somewhat with a twist. The patched wine installed without problems, but when I tried to update it I started getting this error. 

Makefile:318: recipe for target 'dri3.o' failed
make[1]: **\* [dri3.o] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-corazin/aur-wine-d3dadapter-git/src/wine-d3dadapter-git-64-build/dlls/winex11.drv'
Makefile:14358: recipe for target 'dlls/winex11.drv' failed
make: **\* [dlls/winex11.drv] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build wine-d3dadapter-git.
==> Restart building wine-d3dadapter-git ? [y/N]
